name: Rust

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build_linux:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: cargo build --release
    - name: Run tests
      run: cargo test
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v2
      with:
        name: crazyradio-server_linux_amd64
        path: target/release/crazyradio-server
  
  build_windows:
    runs-on: windows-2019
    
    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: cargo build --release
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v2
      with:
        name: crazyradio-server_windows
        path: target/release/crazyradio-server.exe

  build_mac:
    runs-on: macos-10.15
    
    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: cargo build --release
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v2
      with:
        name: crazyradio-server_macos
        path: target/release/crazyradio-server
